draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_font(galmooriSmall)
if(global.language==1) {
	if(whichButton=="bgm")
		draw_text(711,349,"BGM")
	else if(whichButton=="sfx")
		draw_text(711,349,"효과음")
	else if(whichButton=="lang")
		draw_text(711,349,"언어 설정")
	else if(whichButton=="copyr")
		draw_text(711,349,"음악 출처")
	else if(whichButton=="credit")
		draw_text(711,349,"크레딧")
	else if(whichButton=="achi")
		draw_text(711,349,"업적")
} else if(global.language==2) {
	if(whichButton=="bgm")
		draw_text(711,349,"BGM")
	else if(whichButton=="sfx")
		draw_text(711,349,"SFX")
	else if(whichButton=="lang")
		draw_text(711,349,"Language")
	else if(whichButton=="copyr")
		draw_text(711,349,"Music Source")
	else if(whichButton=="credit")
		draw_text(711,349,"Credits")
	else if(whichButton=="achi")
		draw_text(711,349,"Achievements")
}
draw_set_halign(fa_left)
draw_set_valign(fa_top)