instance_create_depth(272,256,5,obj_bc_spawner,{amount:6})
instance_create_depth(480,224,5,obj_snake_square)
instance_create_depth(480,224,5,obj_snake_square)
instance_create_depth(0,0,5,obj_m_spawner,{difficulty:3})
instance_create_depth(0,0,0,obj_lc_spawner,{difficulty:2})
instance_create_depth(0,0,0,obj_rc_spawner,{difficulty:2})
instance_create_depth(0,0,5,obj_spin_spawner,{difficulty:7})
