draw_set_halign(fa_right)
draw_set_valign(fa_middle)
draw_set_font(galmooriSmall)
if(global.language==1)
	draw_text(667,430,"한국어")
else if(global.language==2)
	draw_text(667,430,"English")
draw_set_halign(fa_left)
draw_set_valign(fa_top)